version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Logging in to Docker Hub
      - aws secretsmanager get-secret-value --secret-id dockerHubCredentials --query 'SecretString' --output text > dockerhub_creds.json
      - export DOCKER_USERNAME=$(cat dockerhub_creds.json | jq -r '.username')
      - export DOCKER_PASSWORD=$(cat dockerhub_creds.json | jq -r '.password')
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  pre_build:
    commands:
      - echo Logging into Amazon ECR started on 'date'
      - aws --version
      - echo Logging into Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382529210.dkr.ecr.us-east-1.amazonaws.com
      - echo setting repository URI
      - REPOSITORY_URI=992382529210.dkr.ecr.us-east-1.amazonaws.com/bh-repo
      - echo setting image tag....
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo building and tagging started image on 'date'
      - echo running docker build
      - docker build -t $REPOSITORY_URI:latest .
      - echo tagging the docker image
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing Docker image to Amazon ECR started on 'date'
      - echo pushing to repository
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name...
      - DOCKER_CONTAINER_NAME=bh-container
      - echo writing image definitions file....
      - printf '[{"name":"$s", "imageUri":"$s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
